[default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc_version = '0.8.0'

[profile.local]
rpc_url = 'http://127.0.0.1:8545'

[profile.avalanche]
rpc_url = 'https://api.avax.network/ext/bc/C/rpc'
